version: '3'
services:
  nst-service:
    container_name: nst-container
    image: nst-server:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/:/usr/share/nginx/html:ro
    ports:
      - 80:80
    restart: unless-stopped