version: '3'
services:
  nst-service:
    container_name: nst-container
    image: nvcr.io/nvidia/pytorch:22.01-py3
    ports:
      - 80:2000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped